name: Auto Update README

on:
  schedule:
    - cron: '0 0 * * *'   # runs daily at 5:30 AM IST
  workflow_dispatch:       # allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update README
      run: |
        echo "## Hello Vishvajeet! 👋" > README.md
        echo "Last updated on $(date)" >> README.md

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git commit -m "🔄 Auto-update README"
        git push
