name: Auto Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update README
      run: |
        echo "## Hello Vishvajeet! 👋" > README.md
        echo "Last updated on $(date)" >> README.md

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add README.md || echo "Nothing to add"
        git commit -m "🔄 Auto-update README" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
