name: Daily Streak Commit

on:
  schedule:
    - cron: '0 4 * * *'  # 9:30 AM IST
  workflow_dispatch: {}

jobs:
  commit-daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp in log.txt
        run: echo "Daily log: $(date)" >> log.txt

      - name: Commit and Push
        run: |
          git config --global user.name "vishvajeetmankar"
          git config --global user.email "vishumankar2196@gmail.com"
          git add log.txt
          git commit -m "📅 Daily streak commit" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
