name: Auto Update Timestamp

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 5:30 AM IST
  workflow_dispatch: {}

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp in README
        run: |
          dt=$(TZ='Asia/Kolkata' date +"%A, %d %B %Y, %I:%M %p IST")
          sed -i "s|_Last updated on: .*_|_Last updated on: $dt_|" README.md

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md || echo "Nothing to add"
          git commit -m "🕒 Update timestamp" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
